### ISSUE TITLE
Raspberry Pi 4 unsupported CPU architecture

### ISSUE THREAD

**Issue by aricallen** [urish/node-lsl#6]
Hello, I'm trying to get my Muse (2014 model?) headset to work with my Raspberry Pi 4. I landed here because I was trying to use your `muse-lsl` package and even trying a step lower with [noble](https://github.com/noble/noble) but a simple install and `yarn start` fails because of the `node-lsl`. Reading through the issues on `noble` and `muse-lsl` it seems like no one else has run into this exact error but others have this working on raspi to some level. Looks like your expecting `process.arch` to say `x86` but instead it is saying `arm` and so the script throws an error. Does this seem correct? Any thoughts or workarounds in mind? Thanks in advance

```
pi@raspberrypi:~/Developer/node-lsl $ node index.js
/home/pi/Developer/node-lsl/index.js:42
    throw new Error(`Unsupported CPU architecture for node-lsl: ${process.arch}`);
    ^

Error: Unsupported CPU architecture for node-lsl: arm
    at Object.<anonymous> (/home/pi/Developer/node-lsl/index.js:42:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
pi@raspberrypi:~/Developer/node-lsl $ node --version
v8.16.0
```

**Comment by oori** [comment]
[alexandrebarachant/muse-lsl](https://github.com/alexandrebarachant/muse-lsl) works great on Pi4.  Use that.
